export const IPC_CHANNELS = {
  getSources: 'get-sources',
  windowMinimize: 'win-minimize',
  windowMaximize: 'win-maximize',
  windowClose: 'win-close',
  updaterCheck: 'updater-check',
  updaterInstall: 'updater-install',
  updaterGetInfo: 'updater-get-info',
  updaterSetAutoUpdateEnabled: 'updater-set-auto-update-enabled',
  updaterStatus: 'updater-status',
  openExternalUrl: 'open-external-url',
  logAppend: 'log-append',
  logList: 'log-list',
  logClear: 'log-clear',
  logAdded: 'log-added',
  experimentalCaptureGetEnabled: 'experimental-capture-get-enabled',
  experimentalCaptureSetEnabled: 'experimental-capture-set-enabled',
  audioLoopbackFindProcess: 'audio-loopback-find-process',
  audioLoopbackStart: 'audio-loopback-start',
  audioLoopbackStop: 'audio-loopback-stop',
  audioLoopbackChunk: 'audio-loopback-chunk'
} as const;
