export const CHAT_STRINGS = {
  title: 'Mensagens',
  emptyMessage: 'Ainda não tem nenhuma mensagem. As mensagens não ficam salvas em lugar nenhum — somem quando você sai da sala.',
  inputPlaceholder: 'Escreva uma mensagem... (aceita Markdown — Shift+Enter pra quebrar linha)',
  sendButton: 'Enviar',
  selfSenderLabel: 'Você',
  deleteMessageButton: 'Apagar mensagem',
  deleteConfirmTitle: 'Apagar essa mensagem?',
  deleteConfirmBody: 'Some pra todo mundo na sala. Isso não pode ser desfeito.',
  deleteConfirmCancelButton: 'Cancelar',
  deleteConfirmDeleteButton: 'Apagar',
  editedTag: '(editado)',
  editMessageButton: 'Editar mensagem',
  editInputPlaceholder: 'Editar mensagem...',
  editSaveButton: 'Salvar',
  editCancelButton: 'Cancelar',
  replyButton: 'Responder',
  reactButton: 'Reagir',
  replyPreviewLabel: 'Respondendo a',
  replyCancelButton: 'Cancelar resposta',
  replyToUnknownMessage: 'mensagem apagada'
} as const;
