export const CONTACTS_STRINGS = {
  contactsButton: 'Contatos',
  contactsHint: 'Os amigos que você salvou — chame alguém sem trocar código toda vez.',
  inviteContactsTitle: 'Convidar contatos (opcional)',
  inviteContactsHint:
    'Quem você marcar entra direto na sala, sem precisar de código/senha e sem você ter que aprovar — só funciona se a pessoa estiver com a sala pessoal dela aberta agora.',
  screenTitle: 'Contatos',
  backButton: 'Voltar',
  contactsListTitle: 'Seus contatos',
  noContactsMessage: 'Nenhum contato salvo ainda. Adicione um abaixo.',
  noContactsMatchMessage: 'Nenhum contato encontrado pra essa busca.',
  searchFieldPlaceholder: 'Buscar contato pelo apelido...',
  favoriteContactButton: 'Marcar como favorito',
  unfavoriteContactButton: 'Tirar dos favoritos',
  callContactButton: 'Chamar',
  onlinePresenceLabel: 'Online (sala pessoal aberta)',
  offlinePresenceLabel: 'Offline agora',
  checkingPresenceLabel: 'Verificando...',
  removeContactButton: 'Remover',
  editContactButton: 'Editar',
  editContactSaveButton: 'Salvar',
  editContactCancelButton: 'Cancelar',
  addContactTitle: 'Adicionar contato',
  contactNameFieldLabel: 'Apelido',
  contactNameFieldPlaceholder: 'Como você quer chamar essa pessoa',
  contactIdFieldLabel: 'ID da pessoa',
  contactIdFieldPlaceholder: 'Peça pra ela copiar o "Seu ID" e colar aqui',
  contactPasswordFieldLabel: 'Senha da sala pessoal dela',
  contactPasswordFieldPlaceholder: 'Peça pra ela te passar a senha da sala pessoal dela',
  addContactButton: 'Salvar contato',
  contactFieldsRequiredError: 'Preencha apelido, ID e senha antes de salvar.',
  callingContactStatus: 'Chamando...',
  callContactError: (reason: string) => `Não foi possível conectar (${reason}). A pessoa pode estar offline agora.`,
  personalPasswordMissingPopupTitle: 'Sua sala pessoal está sem senha',
  personalPasswordMissingPopupBody:
    'Você deixou "Abrir automaticamente" ligado, mas sem uma senha definida ela não consegue abrir sozinha (nem manualmente) — toda sala do ZeroHop precisa de senha.',
  personalPasswordMissingPopupSetNowButton: 'Definir senha agora',
  personalPasswordMissingPopupDismissButton: 'Lembrar depois'
} as const;
