export const LOG_STRINGS = {
  screenTitle: 'Logs',
  backButton: '← Voltar',
  emptyMessage: 'Nada registrado ainda.',
  technicalDetailsToggle: 'Detalhes técnicos',
  clearButton: 'Limpar histórico',
  clearConfirmMessage: 'Apagar todo o histórico de logs? Não dá pra desfazer.',
  clearConfirmButton: 'Sim, apagar',
  clearCancelButton: 'Cancelar',
  allCategoriesFilter: 'Tudo',
  categoryLabels: {
    app: 'App',
    room: 'Sala',
    sharing: 'Compartilhamento',
    voice: 'Voz',
    connection: 'Conexão',
    update: 'Atualização',
    hotkeys: 'Teclas de atalho'
  },
  appStartedMessage: (version: string) => `ZeroHop v${version} foi aberto.`,
  roomCreatedMessage: (code: string) => `Você criou a sala ${code}.`,
  roomJoinedMessage: (code: string) => `Você entrou na sala ${code}.`,
  roomLeftMessage: 'Você saiu da sala.',
  memberJoinedMessage: (name: string) => `${name} entrou na sala.`,
  memberLeftMessage: (name: string) => `${name} saiu da sala.`,
  connectionWarningMessage: (label: string) => `A conexão com ${label} está demorando a responder.`,
  connectionEstablishedDirectMessage: (label: string) => `Conexão com ${label} estabelecida direto (sem retransmissão).`,
  connectionEstablishedTurnMessage: (label: string) =>
    `Conexão com ${label} estabelecida via retransmissão (TURN) — consome banda do plano gratuito.`,
  connectionNeverPreparedMessage: (label: string) => `Não foi possível preparar a conexão com ${label}.`,
  connectionTimeoutMessage: (label: string) => `A conexão com ${label} não abriu a tempo.`,
  connectionStatsErrorMessage: (label: string) => `Erro ao verificar o estado da conexão com ${label}.`,
  connectionLostMessage: (label: string) => `Conexão com ${label} caiu (provavelmente fechou o app sem sair da sala).`,
  voiceCallRetryMessage: (label: string) => `A chamada de voz com ${label} não conectou a tempo — tentando de novo.`,
  voiceCallFailedMessage: (label: string) => `Não foi possível estabelecer a chamada de voz com ${label} depois de várias tentativas.`,
  invalidMessageDiscardedMessage: 'Uma mensagem que não seguia o formato esperado foi descartada.',
  peerErrorMessage: 'Erro na conexão P2P.',
  sharingStartedMessage: 'Você começou a compartilhar sua tela.',
  sharingStoppedMessage: 'Você parou de compartilhar sua tela.',
  micActiveMessage: 'Seu microfone foi ativado — você já pode falar na sala.',
  micUnavailableMessage: 'Não foi possível usar o microfone — você está na sala, mas ninguém consegue te ouvir.',
  micDeviceSwitchFailedMessage: 'Não foi possível trocar de microfone.',
  micMutedMessage: 'Você mutou seu microfone.',
  micUnmutedMessage: 'Você ativou seu microfone de novo.'
} as const;
