export const PARTICIPANTS_STRINGS = {
  emptyRoomMessage: 'Ainda não tem mais ninguém na sala. Envie o código pra seus amigos.',
  notSharingMessage: 'Não está compartilhando a tela agora.',
  sharingBadge: 'compartilhando',
  micMutedBadge: 'microfone mutado',
  watchingMyScreenBadge: 'assistindo sua tela',
  notWatchingMyScreenBadge: 'não está assistindo sua tela',
  watchButton: 'Assistir',
  stopWatchingButton: 'Parar de assistir',
  connectingMessage: 'Conectando...',
  noAudioMessage: 'Essa pessoa está compartilhando sem áudio.',
  muteButtonLabel: 'Mudo',
  unmuteButtonLabel: 'Reativar som',
  kickMemberButton: 'Remover da sala',
  defaultMemberName: 'Sem nome',
  addToContactsButton: 'Adicionar aos contatos',
  alreadyContactBadge: 'Já é seu contato',
  addToContactsPasswordLabel: 'Senha da sala pessoal dela',
  addToContactsPasswordPlaceholder: 'Peça pra ela te passar a senha da sala pessoal dela',
  addToContactsConfirmButton: 'Adicionar',
  addToContactsCancelButton: 'Cancelar',
  addToContactsFieldRequiredError: 'Preencha a senha antes de adicionar.'
} as const;
