export const PRE_ROOM_STRINGS = {
  choiceTitle: 'ZeroHop',
  createRoomButton: 'Criar sala nova',
  joinRoomButton: 'Entrar numa sala',
  backButton: 'Voltar',
  nameFieldLabel: 'Seu nome',
  nameFieldPlaceholder: 'Como seus amigos vão te ver',
  avatarFieldLabel: 'Foto de perfil',
  passwordFieldLabel: 'Senha da sala',
  passwordFieldPlaceholder: 'Escolha uma senha pra proteger a sala',
  passwordTooShortError: 'A senha precisa ter pelo menos 4 caracteres.',
  createRoomTitle: 'Criar sala nova',
  creatingRoomStatus: 'Criando sala...',
  createRoomError: (reason: string) => `Não foi possível criar a sala (${reason}). Tente de novo.`,
  joinRoomTitle: 'Entrar numa sala',
  codeFieldLabel: 'Código da sala',
  codeFieldPlaceholder: 'Cole aqui o código que seu amigo te mandou',
  codeRequiredError: 'Digite o código da sala.',
  joinPasswordFieldPlaceholder: 'Digite a senha que seu amigo te passou',
  joiningRoomStatus: 'Entrando na sala...',
  awaitingApprovalStatus: 'Senha confirmada. Aguardando o criador da sala aprovar sua entrada...',
  joinRoomError: (reason: string) => `Não foi possível conectar (${reason}). Tente de novo.`
} as const;
