export const ROOM_STRINGS = {
  roomCodeLabel: 'Código da sala:',
  roomPasswordLabel: 'Senha:',
  leaveRoomButton: 'Sair da sala',
  muteMicButton: 'Mutar mic',
  unmuteMicButton: 'Ativar mic',
  deafenButton: 'Silenciar todos',
  undeafenButton: 'Ouvir todos',
  chooseSourceTitle: 'Escolha o que compartilhar',
  resolutionFieldLabel: 'Resolução',
  fpsFieldLabel: 'FPS',
  audioFieldLabel: 'Áudio',
  audioSameAsVideoOption: 'Junto com o que eu compartilhar',
  audioNoneOption: 'Sem áudio',
  audioOnlyFromOption: (sourceName: string) => `Só o áudio de "${sourceName}"`,
  startSharingButton: 'Compartilhar minha tela',
  saveShareChangesButton: 'Salvar alterações',
  editSharingButton: 'Editar',
  stopSharingButton: 'Parar de compartilhar',
  qualityHint: 'FPS e resolução mais altos exigem mais da sua internet e da de quem for assistir — se engasgar, tente valores menores.',
  audioIndependenceHint:
    'O seletor de áudio é independente do de vídeo: dá pra compartilhar a tela toda e escolher o áudio de só um app específico na lista "Áudio".',
  chooseSourceFirstError: 'Escolha primeiro o que compartilhar.',
  captureError: (reason: string) => `Erro ao capturar a tela: ${reason}`,
  sharingWithAudioStatus: 'Compartilhando sua tela com a sala.',
  sharingAudioFallbackStatus: 'Compartilhando sua tela (sem áudio — não foi possível capturar o áudio escolhido nesta máquina).',
  windowSourceKind: 'Janela',
  screenSourceKind: 'Tela toda',
  chooseSourceKindTitle: 'O que você quer compartilhar?',
  shareEntireScreenOption: 'Tela inteira',
  shareSpecificWindowOption: 'Uma janela específica',
  windowCaptureFocusHint:
    'Compartilhar uma janela específica pode ficar preta se você trocar de janela (Alt+Tab) enquanto ela não está em primeiro plano — isso é uma limitação do Windows com alguns programas, não um bug do app. Se for alternar entre janelas durante o compartilhamento, prefira "Tela inteira".',
  backToSourceKindButton: '← Voltar',
  noWindowSourcesMessage: 'Nenhuma janela disponível pra compartilhar agora.',
  noScreenSourcesMessage: 'Nenhuma tela disponível pra compartilhar agora.',
  participantsTitle: 'Participantes',
  connectionWarning:
    'Não foi possível conectar com alguém da sala depois de um tempo — pode ser um bloqueio de rede/firewall/VPN. Aperte F12 pra ver detalhes no console.',
  cancelShareSetupButton: 'Cancelar',
  sharingActiveLabel: 'Você está compartilhando sua tela.',
  enlargePreviewHint: 'Clique pra ampliar',
  closePreviewHint: 'Clique em qualquer lugar ou aperte Esc pra fechar',
  stageEmptyTitle: 'Nada sendo exibido agora',
  stageEmptyHint: 'Assista alguém da lista de participantes, ou compartilhe a sua tela.',
  hideSidebarButton: 'Ocultar sala',
  showSidebarButton: 'Mostrar sala',
  hideChatButton: 'Ocultar chat',
  showChatButton: 'Mostrar chat',
  joinRequestTitle: (name: string) => `${name} quer entrar na sala`,
  joinRequestHint: 'A senha está correta, mas só você pode confirmar quem entra.',
  joinRequestApproveButton: 'Aceitar',
  joinRequestDenyButton: 'Recusar',
  joinRequestQueueHint: (count: number) => `+${count} outro${count > 1 ? 's' : ''} pedido${count > 1 ? 's' : ''} aguardando`,
  connectionFailedError: 'Não foi possível conectar com a sala',
  createRoomFailedError: 'Não foi possível criar a sala',
  invalidCredentialsError: 'Código ou senha incorretos',
  joinFailedGenericError: 'Não foi possível entrar na sala',
  versionMismatchError: (ownVersion: string, remoteVersion: string) =>
    `Você está na versão v${ownVersion} e a outra pessoa está na v${remoteVersion} — as duas precisam estar na mesma versão pra entrar na mesma sala.`
} as const;
