export const SETTINGS_STRINGS = {
  screenTitle: 'Configurações',
  backButton: '← Voltar',
  audioOutputTab: 'Áudio',
  audioOutputTitle: 'Dispositivo de saída de áudio',
  audioOutputHint: 'Escolha em qual alto-falante ou fone você quer ouvir o áudio de quem está compartilhando.',
  audioOutputFieldLabel: 'Ouvir em',
  systemDefaultAudioOutputOption: 'Padrão do sistema',
  unnamedAudioOutputLabel: (index: number) => `Dispositivo de áudio ${index}`,
  micInputTitle: 'Microfone',
  micInputHint: 'Escolha qual microfone usar pra falar na sala e ajuste a sensibilidade dele.',
  micInputFieldLabel: 'Falar com',
  systemDefaultMicInputOption: 'Padrão do sistema',
  unnamedMicInputLabel: (index: number) => `Microfone ${index}`,
  micSensitivityFieldLabel: 'Sensibilidade do microfone',
  micSensitivityHint: 'Aumente se sua voz está saindo baixa pros outros, ou diminua se estiver estourando/muito alta.',
  noiseSuppressionToggleLabel: 'Supressão de ruído',
  noiseSuppressionHint:
    'Reduz ruídos de fundo (teclado, ventilador, eco) usando o processamento nativo do WebRTC. Vem ligada por padrão; desligue se sua voz estiver saindo robotizada ou "cortando".',
  micPermissionDeniedHint: 'O microfone não foi permitido — você está na sala mesmo assim, mas ninguém consegue te ouvir.',
  grantMicPermissionButton: 'Permitir microfone',
  micPermissionOutsideRoomHint: 'Conceda a permissão do microfone agora pra já estar liberado na próxima vez que entrar numa sala.',
  micPermissionGrantedStatus: 'Permissão concedida.',
  micPermissionStillDeniedStatus: 'Ainda sem permissão — talvez precise liberar o microfone nas configurações do Windows pra este app.',
  experimentalTitle: 'Captura otimizada para jogos (experimental)',
  experimentalHint:
    'Tenta usar a API Windows.Graphics.Capture do Windows em vez do método padrão. Em alguns jogos (principalmente em tela cheia ou com cursor customizado) isso pode resolver: cursor sumindo, imagem travando/piscando ao compartilhar. Mas essa API já causou instabilidade grave — inclusive travamento completo do PC — em pelo menos um computador testado, então vem desligada por padrão.',
  experimentalToggleLabel: 'Ativar captura experimental',
  experimentalRestartHint: 'Precisa reiniciar o app pra fazer efeito (ligando ou desligando).',
  experimentalConfirmTitle: 'Tem certeza?',
  experimentalConfirmBody:
    'Essa opção já travou o PC de um usuário no passado (precisou desligar no botão físico). Pode funcionar perfeitamente no seu computador, ou pode não funcionar — não temos como saber com antecedência de qual grupo o seu PC faz parte. Se travar, é só desligar essa opção de novo (o app volta ao método padrão, que é o que você está usando até agora).',
  experimentalConfirmButton: 'Sim, quero tentar',
  experimentalCancelButton: 'Deixa como está',
  experimentalEnabledLogMessage: 'A captura experimental foi ativada (precisa reiniciar o app).',
  experimentalDisabledLogMessage: 'A captura experimental foi desativada (precisa reiniciar o app).'
} as const;
