export const SETTINGS_STRINGS = {
  screenTitle: 'Configurações',
  backButton: '← Voltar',
  audioOutputTab: 'Áudio',
  audioOutputTitle: 'Dispositivo de saída de áudio',
  audioOutputHint: 'Escolha em qual alto-falante ou fone você quer ouvir o áudio de quem está compartilhando.',
  audioOutputFieldLabel: 'Ouvir em',
  systemDefaultAudioOutputOption: 'Padrão do sistema',
  unnamedAudioOutputLabel: (index: number) => `Dispositivo de áudio ${index}`,
  micInputTitle: 'Microfone',
  micInputHint: 'Escolha qual microfone usar pra falar na sala e ajuste a sensibilidade dele.',
  micInputFieldLabel: 'Falar com',
  systemDefaultMicInputOption: 'Padrão do sistema',
  unnamedMicInputLabel: (index: number) => `Microfone ${index}`,
  micSensitivityFieldLabel: 'Sensibilidade do microfone',
  micSensitivityHint: 'Aumente se sua voz está saindo baixa pros outros, ou diminua se estiver estourando/muito alta.',
  noiseSuppressionToggleLabel: 'Supressão de ruído',
  noiseSuppressionHint:
    'Reduz ruídos de fundo (teclado, ventilador, eco) usando o processamento nativo do WebRTC. Vem ligada por padrão; desligue se sua voz estiver saindo robotizada ou "cortando".',
  micPermissionDeniedHint: 'O microfone não foi permitido — você está na sala mesmo assim, mas ninguém consegue te ouvir.',
  grantMicPermissionButton: 'Permitir microfone',
  micPermissionOutsideRoomHint: 'Conceda a permissão do microfone agora pra já estar liberado na próxima vez que entrar numa sala.',
  micPermissionGrantedStatus: 'Permissão concedida.',
  micPermissionStillDeniedStatus: 'Ainda sem permissão — talvez precise liberar o microfone nas configurações do Windows pra este app.',
  soundEffectsTitle: 'Mixer de efeitos sonoros',
  soundEffectsHint: 'Ajuste o volume de cada grupo de sons separadamente, do seu jeito.',
  soundCategoryInterfaceLabel: 'Interface',
  soundCategoryRoomLabel: 'Sala',
  soundCategoryChatLabel: 'Chat',
  soundCategoryVoiceLabel: 'Chamada de voz',
  soundCategorySharingLabel: 'Compartilhamento',
  uiScaleTitle: 'Escala da interface',
  uiScaleHint: 'Aumenta ou diminui o tamanho de tudo (texto, botões, ícones) — útil se estiver pequeno demais pra sua tela ou visão.',
  hotkeysTitle: 'Teclas de atalho',
  hotkeysHint:
    'Funcionam em qualquer lugar, mesmo com outro programa ou jogo em foco. Clique em "Gravar" e aperte a tecla desejada.',
  micMuteHotkeyLabel: 'Mutar/desmutar microfone',
  deafenHotkeyLabel: 'Silenciar/ativar áudio',
  pushToTalkHotkeyLabel: 'Push-to-talk (segurar pra falar)',
  recordHotkeyButton: 'Gravar',
  recordingHotkeyStatus: 'Aperte uma tecla...',
  recordHotkeyTimeoutStatus:
    'Nenhuma tecla detectada — a captura de teclado global pode não estar disponível no seu sistema (veja em Logs).',
  cancelRecordingHotkeyButton: 'Cancelar',
  clearHotkeyButton: 'Remover',
  noHotkeySetLabel: 'Nenhuma',
  pushToTalkReleaseDelayLabel: 'Atraso pra desligar o mic ao soltar a tecla',
  pushToTalkReleaseDelayHint: 'Evita cortar palavras entre pausas curtas na fala.'
} as const;
