export const UPDATES_STRINGS = {
  modalTitle: 'Atualizações',
  closeButton: 'Fechar',
  statusTab: 'Atualização',
  changelogTab: 'Changelog',
  versionsTab: 'Versões',
  currentVersionLabel: (version: string) => `Versão atual: v${version}`,
  devModeHint: 'Atualização automática só funciona na versão instalada (não no modo de desenvolvimento).',
  checkButton: 'Verificar atualizações',
  statusChecking: 'Verificando...',
  statusAvailable: (version: string) => `Nova versão disponível: v${version}. Baixando automaticamente...`,
  statusNotAvailable: 'Você já está na versão mais recente.',
  statusDownloading: (percent: number) => `Baixando atualização... ${percent}%`,
  statusDownloaded: (version: string) => `Versão v${version} baixada e pronta pra instalar.`,
  statusError: (message: string) => `Erro ao verificar atualização: ${message}`,
  installButton: 'Instalar e reiniciar',
  autoUpdateToggleLabel: 'Atualização automática',
  autoUpdateToggleHint: 'Desligada, o app não verifica nem baixa nada sozinho — útil se você quer ficar numa versão específica de propósito. Você ainda pode verificar manualmente quando quiser.',
  changelogLoading: 'Carregando changelog...',
  changelogError: (reason: string) => `Não foi possível carregar o changelog (${reason}).`,
  versionsLoading: 'Carregando versões...',
  versionsError: (reason: string) => `Não foi possível carregar as versões (${reason}).`,
  versionCurrentBadge: 'atual',
  openDownloadPageButton: 'Abrir página de download',
  switchVersionExplanationTitle: (name: string) => `Trocar para ${name}`,
  switchVersionExplanationBody:
    'Este app não troca de versão sozinho: por segurança, a instalação de uma versão diferente da mais recente sempre precisa ser feita manualmente por você, baixando e rodando o instalador daquela versão. Ao confirmar, vamos abrir a página dessa versão no seu navegador — de lá, baixe o instalador (.exe) e execute-o normalmente. Ele substitui a instalação atual.',
  switchVersionSameVersionHint: 'Lembre-se: para entrar na mesma sala, todo mundo precisa estar usando a mesma versão do app.',
  switchVersionConfirmButton: 'Entendi, abrir no navegador',
  switchVersionCancelButton: 'Cancelar'
} as const;
